---
title       : Temperatures registered in Rosario, Argentina, during the year 2014
subtitle    : 
author      : MMP
job         : Student of Data Science Specialization
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight  # {highlight.js, prettify, highlight}
hitheme     : tango      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## The piece of information you needed

- If there is something you really have to do at least once in your life, is to visit the beautiful Argentinian city of Rosario.
- In order to help you make the decision of doing this trip, this app will show how was the weather like during the last year.
- Just look what is the temperature like along the year, pick the period that you like most, and come to enjoy!

--- .class #id 

## As easy as this:

If you want to see what was the temperature on a particular day:

1. Select the date in the panel on the left.
2. Choose Celsius or Farenheit in the radio buttons.
3. Click submit!

And you'll see the minimum, mean and maximum temperature for that day.

--- .class #id 

## And there's more!

As I'm sure you will want to stay for a complete month in this city, you can choose "Month" in the left panel to see the mean of the registered temperatures for the whole selected month.

--- .class #id 

## Wanting some visualization?

Along with the numbers that inform the temperature, you can see a nice plot as the following to visualize the registry:

```{r, echo=FALSE, fig.width=13}
fileUrl <<- "https://raw.github.com/mpru/DataForProject/master/data.txt"
download.file(fileUrl,destfile="data.txt")
data <- read.table("data.txt",header = T)
data$Date <- as.Date(data$Date, "%m/%d/%Y")

maxCels <- max(data$Max) + 0.05 * max(data$Max)
minCels <- min(data$Min) - 0.05 * min(data$Min)

plot(data$Date, data$Min, type = "l", col = "blue", ylim = c(minCels, maxCels),
    main = "Temperatures registered in Rosario during 2014", xlab = "Date", ylab = "Temperature (°C)")
    lines(data$Date, data$Mean, type = "l", col = "orange")
    lines(data$Date, data$Max, type = "l", col = "red")
    abline(v = as.Date("2014-09-23"), lwd = 2, col = "green")
    grid()
    legend(x = "bottomright", c("Min","Mean","Max"), lty=1, lwd=2,col=c("blue","orange","red"), bty = "n",ncol = 3)


```

